GET https://httpbin.org/get
Foo: Bar

###

POST https://httpbin.org/post
Bar: Baz

{
    "example": "payload"
}

###

PUT https://httpbin.org/put

{
    "foo": "bar"
}

###

GET https://httpbin.org/get?param1=2&param2=3

